### ISSUE TITLE
Badges won’t work in iOS 12.1.1

### ISSUE THREAD

**Issue by itzxeon78** [Alticha/Torngat#10]
On an iPhone6,2 (iPhone 5s) with iOS 12.1.1, Badges launches but it never resprings to apply changes. I already tried to reboot and use it but it never works.

**Comment by daemonspudguy** [comment]
Same here, but on an iPad5,1 (iPad Air 1 WiFi).

**Comment by TreyJS** [comment]
Iphone Xr 12.1.1 tried sidelaoding with cydia impactor and ignition both just result in a white screen app that reboots my phone after about 5 seconds.

**Comment by flitziflitzis** [comment]
It is the same with me. Ios 12.1 on iPhone XS Max.
Download with Cydia impactor and with ignito but both doesnt work. Pls fix it:)

**Comment by luemmel69** [comment]
Yo I´ve got the same issue as TreyJS but on an iPhone 5s on iOS 12.1.2

**Comment by daemonspudguy** [comment]
@TreyJS @luemmel69 @itzxeon78 I just found out it is using voucher_swap, which currently doesn’t support older chips or the A12 for differing reasons. (A7-A8 don’t have enough cache, A12 has issues with CoreTrust collisions.
